### ISSUE TITLE
Bee-Py example doesn't work with Python 3.13

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/bee-hive#78]
When using Python 3.13, running the basic example causes this error:

```bash
$ python -m examples.bee_agent.basic
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/paulschw/i-am-bee/bee-hive/examples/bee_agent/basic.py", line 1, in <module>
    from bee_agent import BeeAgent, LLM
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/bee_agent/__init__.py", line 1, in <module>
    from .agents import BaseAgent, BeeAgent
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/bee_agent/agents/__init__.py", line 1, in <module>
    from .agent import BaseAgent, BeeAgent
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/bee_agent/agents/agent.py", line 10, in <module>
    from bee_agent.llms import (
    ...<5 lines>...
    )
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/bee_agent/llms/__init__.py", line 2, in <module>
    from .llm import BaseLLM, LLM, AgentInput
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/bee_agent/llms/llm.py", line 6, in <module>
    from litellm import completion
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/litellm/__init__.py", line 952, in <module>
    from litellm.litellm_core_utils.litellm_logging import Logging, modify_integration
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 70, in <module>
    from ..integrations.azure_storage.azure_storage import AzureBlobStorageLogger
  File "/home/paulschw/i-am-bee/bee-hive/venv/lib64/python3.13/site-packages/litellm/integrations/azure_storage/azure_storage.py", line 6, in <module>
    from re import S, T
ImportError: cannot import name 'T' from 're' (/usr/lib64/python3.13/re/__init__.py)
```

**Comment by vabarbosa** [comment]
additional context: https://docs.python.org/3.14/whatsnew/3.13.html#id5

**Comment by vabarbosa** [comment]
resolved by updating dependencies (more specifically `litellm`: https://github.com/i-am-bee/bee-py/commit/c2a5d5fb3782f585d4ddb8587c19914a834cbce8)
